-- Up Migration

-- 1. Remover FK e PKs antes de alterar tipos
ALTER TABLE "User" DROP CONSTRAINT "User_roleId_fkey";
ALTER TABLE "User" DROP CONSTRAINT "User_pkey";
ALTER TABLE "Role" DROP CONSTRAINT "Role_pkey";

-- 2. Role: TEXT → SERIAL
ALTER TABLE "Role" DROP COLUMN "id";
ALTER TABLE "Role" ADD COLUMN "id" SERIAL NOT NULL;
ALTER TABLE "Role" ADD CONSTRAINT "Role_pkey" PRIMARY KEY ("id");

-- 3. User id: TEXT → SERIAL
ALTER TABLE "User" DROP COLUMN "id";
ALTER TABLE "User" ADD COLUMN "id" SERIAL NOT NULL;
ALTER TABLE "User" ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");

-- 4. User roleId: TEXT → INTEGER
ALTER TABLE "User" DROP COLUMN "roleId";
ALTER TABLE "User" ADD COLUMN "roleId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ALTER COLUMN "roleId" DROP DEFAULT;
ALTER TABLE "User" ADD CONSTRAINT "User_roleId_fkey"
  FOREIGN KEY ("roleId") REFERENCES "Role"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

-- Down Migration

ALTER TABLE "User" DROP CONSTRAINT "User_roleId_fkey";
ALTER TABLE "User" DROP CONSTRAINT "User_pkey";
ALTER TABLE "User" DROP COLUMN "id";
ALTER TABLE "User" ADD COLUMN "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");
ALTER TABLE "User" DROP COLUMN "roleId";
ALTER TABLE "User" ADD COLUMN "roleId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD CONSTRAINT "User_roleId_fkey"
  FOREIGN KEY ("roleId") REFERENCES "Role"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Role" DROP CONSTRAINT "Role_pkey";
ALTER TABLE "Role" DROP COLUMN "id";
ALTER TABLE "Role" ADD COLUMN "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Role" ADD CONSTRAINT "Role_pkey" PRIMARY KEY ("id");
